receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  # 1. To Langfuse
  otlphttp/langfuse:
    endpoint: "http://langfuse-server:3000/api/public/otel"
    headers:
      Authorization: "${LANGFUSE_AUTH}"

  # 2. To Tempo
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlphttp/langfuse, otlp/tempo ]
